# Config file for automatic testing at travis-ci.org

language: python
python: 2.7

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: make deps

# command to run tests, e.g. python setup.py test
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then py.test --cov-report term-missing --cov=strabo --runslow tests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then make test; fi'
